import json
import os
import re
from pathlib import Path
from typing import Any, Dict, List, Tuple

import aiofiles

from backend.config import settings


class KnowledgeBase:
    def __init__(self, base_path: str = None):
        self.base_path = Path(base_path or settings.knowledge_base_chunks)
        self.summary_file = Path(settings.knowledge_base_file_summary)
        self.summary_json_file = self.summary_file.parent / "summary_demo.json"
        # Hard limits to prevent tool retrieval from exploding token usage.
        self.max_retrieve_files = int(os.getenv("MAX_RETRIEVE_FILES", "6"))
        self.max_chars_per_file = int(os.getenv("MAX_RETRIEVE_CHARS_PER_FILE", "4000"))
        self.max_total_chars = int(os.getenv("MAX_RETRIEVE_TOTAL_CHARS", "12000"))
        self.allow_retrieve_all = os.getenv("ALLOW_RETRIEVE_ALL", "false").lower() == "true"
        # Section retrieval limits for agentic evidence extraction.
        self.max_section_chars = int(os.getenv("MAX_SECTION_CHARS", "1200"))
        self.max_section_total_chars = int(os.getenv("MAX_SECTION_TOTAL_CHARS", "9000"))
        self.max_search_top_k = int(os.getenv("MAX_SEARCH_TOP_K", "10"))
        self._summary_index_cache: List[Dict[str, str]] | None = None

    async def get_file_summary(self) -> str:
        """
        Get knowledge base file summary

        The summary file needs to be generated by an independent script:
        Knowledge-Base-File-Summary/generate.py

        If the summary file does not exist, return a prompt message
        """
        if self.summary_file.exists():
            async with aiofiles.open(self.summary_file, "r", encoding="utf-8") as f:
                return await f.read()

        return (
            "Knowledge Base Summary file not found.\n\n"
            "Please generate it first by running:\n"
            "Knowledge-Base-File-Summary/generate.py\n\n"
            f"Expected file path: {self.summary_file}"
        )

    def _extract_terms(self, text: str) -> set[str]:
        normalized = (text or "").lower()
        terms: set[str] = set()

        for token in re.findall(r"[a-z0-9][a-z0-9._-]{1,}", normalized):
            terms.add(token)

        # Capture Chinese words as bi-grams to get lightweight lexical matching
        # without adding external tokenizer dependencies.
        for cjk_span in re.findall(r"[\u4e00-\u9fff]{2,}", normalized):
            terms.add(cjk_span)
            for i in range(0, len(cjk_span) - 1):
                terms.add(cjk_span[i : i + 2])

        return terms

    def _load_summary_index(self) -> List[Dict[str, str]]:
        if self._summary_index_cache is not None:
            return self._summary_index_cache

        entries: List[Dict[str, str]] = []

        if self.summary_json_file.exists():
            try:
                with open(self.summary_json_file, "r", encoding="utf-8") as f:
                    data = json.load(f)
                for path, summary in data.items():
                    if isinstance(summary, list):
                        merged = " ; ".join(
                            chunk.get("summary", "") for chunk in summary if isinstance(chunk, dict)
                        ).strip()
                    else:
                        merged = str(summary).strip()
                    entries.append({"path": str(path), "summary": merged})
            except Exception as e:
                print(f"[WARN] Failed to parse {self.summary_json_file}: {e}")

        if not entries:
            for md_file in sorted(self.base_path.rglob("*.md")):
                rel_path = str(md_file.relative_to(self.base_path)).replace("\\", "/")
                entries.append({"path": rel_path, "summary": ""})

        self._summary_index_cache = entries
        return entries

    def update_summary_entry(self, relative_path: str, summary: str) -> None:
        """Update or create one path entry in summary_demo.json for searchable ingestion."""
        path_key = (relative_path or "").strip().replace("\\", "/").lstrip("/")
        if not path_key:
            return

        payload: Dict[str, Any] = {}
        if self.summary_json_file.exists():
            try:
                with open(self.summary_json_file, "r", encoding="utf-8") as f:
                    existing = json.load(f)
                if isinstance(existing, dict):
                    payload = existing
            except Exception as e:
                print(f"[WARN] Failed to load summary index for update: {e}")

        payload[path_key] = (summary or "").strip()
        self.summary_json_file.parent.mkdir(parents=True, exist_ok=True)
        with open(self.summary_json_file, "w", encoding="utf-8") as f:
            json.dump(payload, f, ensure_ascii=False, indent=2)

        # Force reload on next search_paths call.
        self._summary_index_cache = None

    async def search_paths(self, query: str, top_k: int = 5) -> str:
        entries = self._load_summary_index()
        if not entries:
            return "No searchable paths found in knowledge base."

        safe_top_k = max(1, min(int(top_k or 5), self.max_search_top_k))
        query_terms = self._extract_terms(query)
        query_text = (query or "").lower()
        scored: List[Tuple[float, Dict[str, str]]] = []

        for entry in entries:
            corpus = f"{entry['path']} {entry['summary']}".lower()
            corpus_terms = self._extract_terms(corpus)
            overlap = query_terms & corpus_terms

            score = float(len(overlap) * 3)
            for term in query_terms:
                if len(term) >= 2 and term in corpus:
                    score += 1.2

            # Slight preference for leaf files over directories in candidate list.
            if entry["path"].endswith(".md"):
                score += 0.2

            if score > 0:
                scored.append((score, entry))

        if not scored:
            # Fallback: if lexical overlap is empty, return first files so the model
            # can continue, but mark score as 0.
            fallback = []
            for entry in entries[:safe_top_k]:
                fallback.append(
                    {"path": entry["path"], "score": 0.0, "summary": entry["summary"][:200]}
                )
            return json.dumps(
                {"query": query_text, "top_k": safe_top_k, "candidates": fallback},
                ensure_ascii=False,
            )

        scored.sort(key=lambda x: (-x[0], x[1]["path"]))
        candidates = []
        for score, entry in scored[:safe_top_k]:
            candidates.append(
                {
                    "path": entry["path"],
                    "score": round(score, 3),
                    "summary": entry["summary"][:260],
                }
            )

        return json.dumps(
            {"query": query_text, "top_k": safe_top_k, "candidates": candidates},
            ensure_ascii=False,
        )

    async def retrieve_sections(
        self, file_paths: List[str], query: str, max_sections_per_file: int = 2
    ) -> str:
        if not file_paths:
            return "No file paths provided for retrieve_sections."

        safe_max_sections = max(1, min(int(max_sections_per_file or 2), 4))
        resolved_files = self._resolve_paths_to_files(file_paths)
        if not resolved_files:
            return "No matching files found for provided paths."

        query_terms = self._extract_terms(query)
        results: List[str] = []
        notes: List[str] = []
        total_chars = 0
        base_root = self.base_path.resolve()

        for file_path in resolved_files:
            content = await self._read_file(file_path)
            sections = self._split_into_sections(content)
            ranked_sections = self._rank_sections(sections, query_terms)
            selected = ranked_sections[:safe_max_sections]

            for section_idx, (score, heading, body) in enumerate(selected, start=1):
                clipped = body
                if len(clipped) > self.max_section_chars:
                    clipped = clipped[: self.max_section_chars]
                    clipped += f"\n\n[Truncated section to {self.max_section_chars} chars]"

                try:
                    rel = str(file_path.resolve().relative_to(base_root)).replace("\\", "/")
                except Exception:
                    rel = file_path.name
                header = (
                    f"[[FILE:{rel} | SECTION:{section_idx} | SCORE:{score:.2f} "
                    f"| HEADING:{heading}]]"
                )
                block = f"{header}\n\n{clipped}"

                if total_chars + len(block) > self.max_section_total_chars:
                    notes.append(
                        f"Reached section total char limit ({self.max_section_total_chars}). "
                        "Refine with fewer file paths."
                    )
                    break

                results.append(block)
                total_chars += len(block)

            if total_chars >= self.max_section_total_chars:
                break

        if not results and notes:
            return "\n".join(notes)

        final_content = "\n\n==========\n\n".join(results)
        if notes:
            final_content += "\n\n----------\n\n" + "\n".join(f"[NOTE] {note}" for note in notes)

        return final_content

    def _split_into_sections(self, content: str) -> List[Tuple[str, str]]:
        lines = content.splitlines()
        sections: List[Tuple[str, str]] = []
        current_heading = "intro"
        current_lines: List[str] = []

        def flush():
            body = "\n".join(current_lines).strip()
            if body:
                sections.append((current_heading, body))

        for line in lines:
            if line.lstrip().startswith("#"):
                flush()
                current_heading = line.strip("# ").strip() or "section"
                current_lines = []
                continue
            current_lines.append(line)

        flush()

        if sections:
            return sections

        # Fallback split when no markdown heading exists.
        raw = content.strip()
        if not raw:
            return []

        chunk_size = 800
        chunks: List[Tuple[str, str]] = []
        for i in range(0, len(raw), chunk_size):
            chunks.append((f"chunk_{i // chunk_size + 1}", raw[i : i + chunk_size]))
        return chunks

    def _rank_sections(
        self, sections: List[Tuple[str, str]], query_terms: set[str]
    ) -> List[Tuple[float, str, str]]:
        ranked: List[Tuple[float, str, str]] = []
        for heading, body in sections:
            corpus = f"{heading} {body}".lower()
            section_terms = self._extract_terms(corpus)
            overlap = query_terms & section_terms
            score = float(len(overlap) * 3)
            for term in query_terms:
                if len(term) >= 2 and term in corpus:
                    score += 1.1
            ranked.append((score, heading, body))

        ranked.sort(key=lambda item: (-item[0], -len(item[2])))
        return ranked

    def _resolve_paths_to_files(self, file_paths: List[str]) -> List[Path]:
        files: List[Path] = []
        seen: set[str] = set()
        stop = False
        base_root = self.base_path.resolve()

        for raw_path in file_paths:
            if stop:
                break
            requested_path = (raw_path or "").strip()
            if not requested_path:
                continue

            if requested_path == "/":
                candidates = sorted(self.base_path.rglob("*.md")) if self.allow_retrieve_all else []
            else:
                try:
                    full_path = (self.base_path / requested_path.lstrip("/")).resolve()
                    full_path.relative_to(base_root)
                except Exception:
                    continue
                if full_path.is_dir():
                    candidates = sorted(full_path.rglob("*.md"))
                elif full_path.is_file():
                    candidates = [full_path]
                else:
                    continue

            for candidate in candidates:
                try:
                    candidate_resolved = candidate.resolve()
                    candidate_resolved.relative_to(base_root)
                    rel = str(candidate_resolved.relative_to(base_root)).replace("\\", "/")
                except Exception:
                    continue
                if rel in seen:
                    continue
                seen.add(rel)
                files.append(candidate_resolved)
                if len(files) >= self.max_retrieve_files:
                    stop = True
                    break

        return files

    async def retrieve_files(self, file_paths: List[str]) -> str:
        results: List[str] = []
        notes: List[str] = []
        collected_files = 0
        total_chars = 0
        stop_retrieval = False

        for file_path in file_paths:
            if stop_retrieval:
                break

            requested_path = (file_path or "").strip()
            if not requested_path:
                continue

            if requested_path == "/":
                if not self.allow_retrieve_all:
                    notes.append(
                        'Global retrieval "/" is disabled to control token usage. '
                        "Please request specific files or directories."
                    )
                    continue
                md_files = sorted(self.base_path.rglob("*.md"))
            else:
                full_path = self.base_path / requested_path.lstrip("/")
                if full_path.is_dir():
                    print(f"[DEBUG] Retrieving directory: {requested_path}")
                    md_files = sorted(full_path.rglob("*.md"))
                elif full_path.is_file():
                    print(f"[DEBUG] Retrieving file: {requested_path}")
                    md_files = [full_path]
                else:
                    notes.append(f"Path not found: {requested_path}")
                    continue

            for md_file in md_files:
                if collected_files >= self.max_retrieve_files:
                    notes.append(
                        f"Reached file limit ({self.max_retrieve_files}). "
                        "Refine to a smaller set of paths."
                    )
                    stop_retrieval = True
                    break

                content = await self._read_file(md_file)
                original_len = len(content)

                if original_len > self.max_chars_per_file:
                    content = content[: self.max_chars_per_file]
                    content += (
                        f"\n\n[Truncated file content: first {self.max_chars_per_file} "
                        f"of {original_len} characters]"
                    )

                relative_path = md_file.relative_to(self.base_path)
                formatted = f"[[FILE:{relative_path}]]\n\n{content}"

                if total_chars + len(formatted) > self.max_total_chars:
                    notes.append(
                        f"Reached total content limit ({self.max_total_chars} chars). "
                        "Refine to fewer paths or specific files."
                    )
                    stop_retrieval = True
                    break

                results.append(formatted)
                collected_files += 1
                total_chars += len(formatted)
                print(
                    f"[DEBUG] Added file: {relative_path}, chunk length: {len(formatted)}, "
                    f"total length: {total_chars}"
                )

        if not results and notes:
            return "\n".join(notes)

        final_content = "\n\n==========\n\n".join(results)
        if notes:
            final_content += "\n\n----------\n\n" + "\n".join(f"[NOTE] {note}" for note in notes)

        print(
            f"[DEBUG] Total content length: {len(final_content)}, files: {len(results)}, "
            f"notes: {len(notes)}"
        )
        return final_content

    async def _read_file(self, file_path: Path) -> str:
        try:
            async with aiofiles.open(file_path, "r", encoding="utf-8") as f:
                return await f.read()
        except Exception as e:
            return f"Error reading file: {str(e)}"

    def list_files(self) -> Dict:
        def scan_dir(path: Path) -> Dict:
            result = {"type": "directory", "name": path.name, "children": []}

            if not path.exists():
                return result

            items = sorted(path.iterdir(), key=lambda x: (not x.is_dir(), x.name))

            for item in items:
                if item.name.startswith("."):
                    continue

                if item.is_dir():
                    result["children"].append(scan_dir(item))
                else:
                    result["children"].append(
                        {
                            "type": "file",
                            "name": item.name,
                            "path": str(item.relative_to(self.base_path)),
                        }
                    )

            return result

        return scan_dir(self.base_path)


knowledge_base = KnowledgeBase()
